# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20171220_1645'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='MeasuredIngredient',
        ),
    ]
