# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20171220_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuredingredient',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='measuredingredient',
            name='units',
            field=models.CharField(blank=True, choices=[('c', 'cup')], max_length=128),
        ),
    ]
